### PR TITLE
Operate on one asset per Dandiset at a time

### LINKED ISSUE #24: Serialize processing within each dandiset
fsspec has issues with parallel/multi-threaded execution.  As a workaround we can for now just make it all serial within each dandiset if there is an easy way for `async` to pretty much become `sync` , i.e. not to proceed to the next asset until it is done with the previous one.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #24.

This PR includes #26.

This PR takes the easy approach of just setting the number of per-Dandiset workers to one.  There will still be multiple tasks doing I/O on a given Dandiset at once (one task iterating over directories, the other running one test on one asset at a time).  This also makes it easy to revert to processing multiple assets at once in the future by just setting the variable to a larger number again.

### CODE REVIEW

**Comment by yarikoptic** [comment]
Looked at https://github.com/dandi/dandisets-healthstatus/pull/28/commits/e156f7b072412df9bb2409d3c46776ff02e4b8f9 1-liner.

I will merge it, but could you please check on e.g. a choice of 2 dandisets  with stock fsspec/datalad-fuse that we are doing ok and not trying to open simultaneously multiple assets/files within each of those dandisets?

**Comment by jwodder** [comment]
@yarikoptic How exactly should I check that?

**Comment by yarikoptic** [comment]
I would have looked at the logs (first ensure that I do log) that we do not start testing/opening a new asset in the dandiset before we are done with the previous one.  Sure thing could also be `strace`ing the process on open/close but it would be too noisy I guess.

**Comment by jwodder** [comment]
@yarikoptic Asset testing appear to be properly non-parallel now.

**Pull request merged**
