### PR TITLE
Replace datalad-fuse with davfs2

### LINKED ISSUE #76: Switch deployment on drogon to use dandidav + davfs2 instead of datalad-fuse
Follow up to results from

- #67

### PR DESCRIPTION
**Pull request by jwodder**
Closes #76.

After this is merged, `~dandi/cronlib/dandisets-healthstatus` on drogon will have to be updated to the new code (manually?).

### CODE REVIEW

**Review by yarikoptic — APPROVED** [review]
One minor comment but otherwise -- let's do it!  Please merge/deploy on drogon. 

I have interrupted, saved, pulled, pushed results in a running session under screen on drogon, so it is all in your hands now.

**Comment by jwodder** [comment]
@yarikoptic 

* `ask_auth` needs to be set to 0 in `/etc/davfs2/davfs2.conf`
* It appears that `dandi@drogon` does not have permission to run the appropriate `mount` & `umount` commands via passwordless `sudo`.  At the very least, `sudo -ln` complains that a password is required.
    * Based on [this comment](https://github.com/dandi/dandisets-healthstatus/pull/67#discussion_r1634988688), you set up `sudo` for `jwodder`, but that's not the user we're running `dandisets-healthstatus` under.

**Comment by yarikoptic** [comment]
- done
- done
```
dandi ALL=(ALL:ALL) NOPASSWD: /usr/bin/umount /tmp/dandisets-fuse
dandi ALL=(ALL:ALL) NOPASSWD: /usr/bin/mount -t davfs https\://webdav.dandiarchive.org /tmp/dandisets-fuse
dandi ALL=(ALL:ALL) NOPASSWD: /usr/bin/umount /mnt/backup/dandi/dandisets-healthstatus/dandisets-fuse
dandi ALL=(ALL:ALL) NOPASSWD: /usr/bin/mount -t davfs https\://webdav.dandiarchive.org /mnt/backup/dandi/dandisets-healthstatus/dandisets-fuse
```

**Comment by jwodder** [comment]
@yarikoptic The setup should be complete now.  Should I just run it in one of my screen sessions or leave that up to you?

**Comment by jwodder** [comment]
@yarikoptic Problem: The code previously recorded the hash of the current commit of each Dandiset repository, but with davfs2, we don't have access to that information.

**Comment by yarikoptic** [comment]
that's interesting! we need some kind of a notion of a version, e.g. last-modified-date. Could you query from dandi-archive API per each dandiset? 

we are going through drafts only avoiding releases, right?

**Comment by yarikoptic** [comment]
hold on -- you expose that in webdav:

image

does davfs2 expose it as mtime for the `draft/` folder ? if so -- take that and be done?

**Comment by jwodder** [comment]
@yarikoptic The script seems to be running fine now, but now just traversing Dandiset file hierarchies seems slower than before.

**Comment by yarikoptic** [comment]
how much slower? my "diagnostic" is the fact that there is barely any python or MATLAB cpu busy tasks :-/

**Comment by yarikoptic** [comment]
it might relate to 
- https://github.com/dandi/dandidav/issues/118
as when I `tail -f` the current log file on drogon:/mnt/backup/dandi/heroku-logs/dandidav  it "pauses" at `heroku[web.1]: Error R14 (Memory quota exceeded)` although it could be red-herring.

**Comment by jwodder** [comment]
@yarikoptic I had to restart the script in order to apply a fix.  Looking at the script's output now, just the listing of the `dandisets/` directory took 30 seconds to get from 000003 to 000026, at which point it got stuck for three minutes, then four more entries were read in 6 seconds, and it now seems to be alternating between stalling for several minutes and retrieving small numbers of entries.  I do not have any timings for datalad-fuse to compare against.

Before you propose any explanations, let me point out that requests to `dandidav` to list the entries of `dandisets/` are responded to with the complete directory listing, so this is presumably davfs2's fault for not caching appropriately.  It seems v1.7.0 of davfs2 added caching, [but it ended up making things slower](https://savannah.nongnu.org/support/?110764).

**Comment by jwodder** [comment]
@yarikoptic I'm almost done rewriting the code to traverse Dandisets via the Archive API instead of mounted-WebDAV (as discussed in the meeting last week).  However, there are issues with updating the `test-files` subcommand (for running a test on a local file and optionally saving the test results to the Dandiset's `status.yaml`).  Do we want to keep this subcommand?  What about keeping its ability to save to `status.yaml`?  If yes to both, should the command assume that the given file paths are always in a WebDAV mount?  If not, how should the Dandiset ID and asset path be determined?

**Comment by yarikoptic** [comment]
Do we have `dandiset.yaml` in the top of the dandiset?  If yes -- just traversal up until hitting it and that would give you ID and top path to deduce asset path. Cache results of such helper function per each folder value so we do not re-traverse without need.

Can't check now since I believe davfs2 is simply hanging and thus two hanging jobs I have mentioned last week:

```
dandi    4133314  0.0  0.0      0     0 ?        D    Jun29   0:02 [python]
dandi    4188696  0.0  0.0 422664  4408 ?        D    Jun29   0:10 /home/dandi/cronlib/dandisets-healthstatus/venv/bin/python /home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/healthstatus/pynwb_open_load_ns.py /mnt/backup/dandi/dandisets-healthstatus/dandisets-fuse/dandisets/000045/draft/sub-01be78e7-8741-4b40-bd64-79ed745431b5/sub-01be78e7-8741-4b40-bd64-79ed745431b5_ses-f6f55a42-6105-4cc9-9c8c-3d3264828b8b_behavior+image.nwb
dandi    4188715  0.0  0.0 414872  4420 ?        D    Jun29   0:02 /home/dandi/cronlib/dandisets-healthstatus/venv/bin/python /home/dandi/cronlib/dandisets-healthstatus/venv/lib/python3.8/site-packages/healthstatus/pynwb_open_load_ns.py /mnt/backup/dandi/dandisets-healthstatus/dandisets-fuse/dandisets/000059/draft/sub-MS12/sub-MS12_ses-Peter-MS12-170719-095305-concat_desc-raw_ecephys.nwb
dandi    4189021  0.0  0.0      0     0 ?        Zl   Jun29   0:02 [python] <defunct>
dandi    4189095  0.0  0.0      0     0 ?        Zl   Jun29   0:02 [python] <defunct>
```

those should be killed, davfs2 restarted.

**Comment by jwodder** [comment]
@yarikoptic 

> Do we have `dandiset.yaml` in the top of the dandiset?

If `test-files` is run on a clone, copy, or WebDAV-mount of a Dandiset, yes.  However, if it's run on a davfs2 mount, experience suggests that traversing upwards looking for a `dandiset.yaml` will be slow.

Moreover, if updating `status.yaml`, currently `test-files` needs to traverse the whole of the Dandiset it's operating on in order to get all asset paths in order to prune assets from `status.yaml` that have since been deleted.  The options for handling this are:

* Traverse the filesystem normally — will be slow if using a davfs2 mount
* Get the list of assets from the Archive API — If the local Dandiset is not up to date with the archive (which can happen when not using a WebDAV mount), this can lead to problems, such as the very file that was tested being deleted from `status.yaml`.
* Add a CLI option for selecting one of the above two behaviors
* Remove `test-files`'s behavior of pruning deleted assets

Which one should I go with?

> those should be killed, davfs2 restarted.

I ran `kill -9` on the `pynwb_open_load_ns.py` last week, but they're still stuck.  I don't know what those zombie processes are.  I sent you a message in Slack asking you to use `sudo` to kill the davsf2 process.  I tried unmounting the davfs2 mount when I started writing this comment, but the process has just been hanging since.

**Comment by yarikoptic** [comment]
> However, if it's run on a davfs2 mount, experience suggests that traversing upwards looking for a `dandiset.yaml` will be slow.

we do not even need to list the directory, just rely on `os.path.lexists` or alike while lru caching the call so that for a folder we never do it twice through runtime of that process. Moreover could be optimized that if any of the parents already known to have `dandiset.yaml` - no need to ask for any child folder. This way it would literally be once per dandiset traversal up.

**Comment by jwodder** [comment]
@yarikoptic Please address the rest of my comment as well.

**Comment by yarikoptic** [comment]
Re `test-files` -- couldn't we just completely disable dealing with the files which are not given to the `test-files` invocation, i.e. pruning them etc?  Pruning deleted paths in general should probably be the job for "dandiset-wide" operation (even if we randomly select only some to go through).

**Comment by jwodder** [comment]
@yarikoptic Yes, that is option number 4.

**Comment by yarikoptic** [comment]
Cool, let's go with it

**Comment by jwodder** [comment]
@yarikoptic Another problem: When running `test-files` on a Dandiset, what should be done about updating the `draft_modified` timestamp in `status.yaml`?  Should it be updated and, if so, to what value/how should that value be obtained?  What if `status.yaml` does not exist yet or has not yet been updated to use `draft_modified`?

**Comment by yarikoptic** [comment]
For `test-files` -- i.e. running test on specific files only -- I do not think we should update `draft_modified` .  It is mostly an interface to troubleshoot errors and timeouts while also "not wasting" doing so and possibly updating those files records. As such, can avoid concerning itself with any dandiset wide (removal of gone entries, draft_modifed, etc) operations.

**Pull request merged**
